### ISSUE TITLE
Calagator iframe is blank

### ISSUE THREAD

**Issue by bryanstearns** [pdxruby/preshow#3]
The Calagator slide's iframe is supposed to include a current image from http://calagator.org, but the iframe is blank.

Loading the site in Chrome with the console open shows this error:

```
Refused to display 'http://calagator.org/' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.
```

which means that Calagator is telling the browser to leave the iframe blank, a good policy to prevent clickjacking attacks.

I see these choices:
- We could show a static image instead of an iframe
- We could get the nice Calagator folks to change their X-Frame-Options setting

I don't think there's a workable alternative to SAMEORIGIN for Calagator: the only options are DENY, SAMEORIGIN, and ALLOW-FROM. If Calagator doesn't actually use iframes itself, it might be reasonable for it to use `ALLOW-FROM http://pdxruby.github.io/` to allow only us to iframe it. Or, it might be possible to get Calagator's webserver (which I think is configured to serve pages with this option) to only set the X-Frame-Options header for pages other than the front page (or better, to serve a page for us to include without X-Frame-Options from a different route).

Any other possibilities?

**Comment by vosechu** [comment]
The only other possibility is that we could ajax it using JSONP, create an iframe, and paste the content from the ajax request. Which is... gross to say the least. I really like the idea of doing the custom ALLOWFROM.

**Comment by bryanstearns** [comment]
Another idea (which would also take a bit of Calagator work) is embedded in RFC7034 (which documents the X-Frame-Options header): Calagator could take a URL querystring parameter that would let it dynamically replace the SAMEORIGIN value with ALLOW-FROM with the querystring URL, if the querystring URL is on a whitelist. See https://tools.ietf.org/html/rfc7034#page-8

**Comment by reidblomquist** [comment]
PR with static logo image here - #2

**Comment by vosechu** [comment]
When I looked at that PR it occurred to me that maybe we just need a big screenshot? People don't actually read calagator from within that iframe right?
<img width="723" alt="calagator__portland_s_tech_calendar" src="https://cloud.githubusercontent.com/assets/11463/12772682/5ae6cfc8-c9e8-11e5-916a-fbbbeea66bc7.png">

**Comment by reidblomquist** [comment]
Not opinionated one way or the other, have no idea how hard it'd be to get around x-origin on the Calagator side of things, but it's worth a shot. I _think_ the drive behind an iframe isn't so much that people want to actually _read_ it, but that the embedded representation is kept current automatically. Thought a logo might be simpler since they're (somewhat) timeless :hourglass: Will happily update that PR with whatever is decided to be most appropriate

**Comment by vosechu** [comment]
Logo seems like a great way to go for now. +1 from me. 

"Make easily reversible decisions quickly" he intones under his breath.

**Comment by reidab** [comment]
What I'm curious to know is what changed about the Calagator server in the months since I originally added the iframe to the slides. Is this even something that we changed on the server, or have browsers just gotten better at enforcing these origin policies recently?

**Comment by reidab** [comment]
Okay, I looked into it a bit. We aren't using iframes on Calagator itself, and didn't intentionally make this change. It came along with our upgrade to Rails 4, which sets X-Frame-Options to SAMEORIGIN by default.

I don't see much of a security issue with allowing embedding of the entire calagator.org site, since it's not like there are any authenticated sessions to hijack…
